# Generated by Django 5.1.3 on 2024-12-02 08:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='shoe_size',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(30, message='Shoe size cannot be smaller than 30'), django.core.validators.MaxValueValidator(50, message='Shoe size cannot be larger than 50')]),
        ),
    ]
